import os
from datetime import datetime

VAULT_PATH = os.path.expanduser("~/Desktop/mitchel")

def save_note(title, content, folder="Mitchell Reports"):
    folder_path = os.path.join(VAULT_PATH, folder)
    os.makedirs(folder_path, exist_ok=True)

    safe_title = "".join(c for c in title if c.isalnum() or c in " -_").strip()
    timestamp = datetime.now().strftime("%Y-%m-%d %H%M")
    filename = f"{timestamp} - {safe_title}.md"
    filepath = os.path.join(folder_path, filename)

    with open(filepath, "w") as f:
        f.write(f"# {title}\n\n")
        f.write(f"*Generated by Mitchell on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}*\n\n")
        f.write(content)

    return filepath

def read_note(filename, folder="Mitchell Reports"):
    filepath = os.path.join(VAULT_PATH, folder, filename)
    if not os.path.exists(filepath):
        return None
    with open(filepath, "r") as f:
        return f.read()

def list_notes(folder="Mitchell Reports"):
    folder_path = os.path.join(VAULT_PATH, folder)
    if not os.path.exists(folder_path):
        return []
    return [f for f in os.listdir(folder_path) if f.endswith(".md")]
